[wandb]
mode = "online"                         # "online", "offline", "disabled"
entity = "isamu"
project = "finetune-ldm-ip-adapter"

[extra_training]
automatic_mixed_precision = true
unet_checkpoint = "checkpoints/unet.safetensors"
text_encoder_checkpoint = "checkpoints/CLIPTextEncoderL.safetensors"
lda_checkpoint = "checkpoints/CLIPTextEncoderL.safetensors"
image_encoder_checkpoint = "checkpoints/dinov2_vitl14_reg4_pretrain.safetensors"

[unet]
requires_grad = false

[text_encoder]
requires_grad = false

[lda]
requires_grad = false

[image_encoder]
requires_grad = false

[uncond_token]

[image_proj]

[ip_adapter]
image_encoder_type = "dinov2_vitl14_reg4"
resolution = 518
scale = 1.0
inference_scale = 1.0
use_timestep_embedding = true
fine_grained = true
initialize_model = true
initializer_range = 0.02
use_rescaler = true
weighted_sum = true

[training]
duration = {"number" = 100000000, "unit" = "step"}
seed = 9752
batch_size = 46
gradient_accumulation = {"number" = 16, "unit" = "step"}
evaluation_interval = {"number" = 500, "unit" = "step"}
evaluation_seed = 9752
dtype = "bfloat16"
device="cuda"
gradient_clipping_max_norm=2.0

[optimizer]
optimizer = "AdamW8bit"  # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
# learning_rate = 5e-4
learning_rate = 5e-5
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[lr_scheduler]
type = "ConstantLR"
update_interval = "1:step"
# max_steps = 2000
# eta_min = 1e-6
# warmup = "500:step"

[dataset]
horizontal_flip_probability = 0.0
image_drop_rate = 0.05
text_drop_rate = 0.05
text_and_image_drop_rate = 0.05
cache_dir = "/home/isamu/tmp"
shuffle = true
cache_limit = "100gb"
is_mosaic = true
is_webdataset = false
only_image = true
dataset_workers = 4

[save_adapter]
checkpoint_steps = 1000
save_folder = "/home/isamu/checkpoints/test"

[test_ldm]
num_inference_steps = 30
num_images_per_prompt = 1
prompts = [
    "A dog flying over a castle",
    "Cute cats watching a tv",
    "A ferret on top of a sky scraper",
    "Pink flamingo playing soccer"
]
validation_image_paths = [
    "tests/weights/frida.jpg",
    "tests/weights/cute_cats.jpg",
    "tests/weights/ferret.jpg",
    "tests/weights/pink_flamingo.jpg"
]
[compute_grad_norms]

[compute_param_norms]
