[wandb]
mode = "online"                         # "online", "offline", "disabled"
entity = "isamu"
project = "finetune-ldm-ip-adapter"

[ldm]
offset_noise = 0
# snr_gamma = 5

[unet]
checkpoint = "tests/weights/unet.safetensors"
requires_grad = false

[text_encoder]
# checkpoint = "tests/weights/CLIPLWithProjection.safetensors"
checkpoint = "tests/weights/CLIPTextEncoderL.safetensors"
requires_grad = false

[lda]
checkpoint = "tests/weights/lda.safetensors"
requires_grad = false

[image_encoder]
checkpoint = "tests/weights/dinov2_vitl14_reg4_pretrain.safetensors"
requires_grad = false

[image_proj]

[adapter]
image_encoder_type = "dinov2_vitl14_reg4"
resolution = 518
scale = 1.0
inference_scale = 1.0
use_pooled_text_embedding = false
use_timestep_embedding = true
fine_grained = true
initialize_model = true
initializer_range = 0.02
use_bias = true
use_rescaler = true
save_folder = "/home/isamu/checkpoints/full_training"
image_embedding_div_factor = 1
pooled_text_div_factor = 10
layernorm_dino = false
weighted_sum = true

[training]
duration = {"number" = 1000000, "unit" = "step"}
seed = 9752
# batch_size = 4
# gradient_accumulation = {"number" = 64, "unit" = "step"}
batch_size = 17
gradient_accumulation = {"number" = 16, "unit" = "step"}
evaluation_interval = {"number" = 500, "unit" = "step"}
evaluation_seed = 9752
dtype = "bfloat16"
# dtype = "float32"
dataset_workers=8
checkpoint_interval = {"number" = 10000, "unit" = "step"}
device="cuda"
amp = true

[optimizer]
optimizer = "AdamW8bit"  # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
# learning_rate = 5e-4
learning_rate = 5e-5
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"
# max_steps = 2000
# eta_min = 1e-6
# warmup = "500:step"

[dataset]
hf_repo = "1aurent/unsplash-lite-palette"
webdataset = true
train_shards_path_or_url = "pipe:gsutil cp gs://bounty-program-data/photo-concept-bucket-webdataset_preencoded/{00000..00056}.tar -"
revision = "main"
split = "train"
horizontal_flip_probability = 0.0
resize_image_min_size = 512
resize_image_max_size = 518
center_crop_size = 512
filter_min_image_size = false
image_drop_rate = 0.05
text_drop_rate = 0.05
text_and_image_drop_rate = 0.05
to_wds = false
pre_encode =  true
image_column = "image"
caption_column = "ai_description"
download_images = true
save_path = "/home/isamu/unsplash_pre_encode_15k"
dataset_length = 15000
zero_uncond = false

# [checkpointing]
# save_folder = "/home/isamu/checkpoints"
# save_interval = {"number" = 1, "unit" = "step"}

[test_ldm]
num_inference_steps = 30
num_images_per_prompt = 1
prompts = [
    "A dog flying over a castle",
    "Cute cats watching a tv",
    "A ferret on top of a sky scraper",
    "Pink flamingo playing soccer"
]
validation_image_paths = [
    "tests/weights/frida.jpg",
    "tests/weights/cute_cats.jpg",
    "tests/weights/ferret.jpg",
    "tests/weights/pink_flamingo.jpg"
]
[compute_grad_norms]

[compute_param_norms]

[save_adapter]