[wandb]
mode = "online"                         # "online", "offline", "disabled"
entity = "isamu"
project = "finetune-ldm-ip-adapter"

[extra_training]
automatic_mixed_precision = true
unet_checkpoint = "checkpoints/unet.safetensors"
text_encoder_checkpoint = "checkpoints/CLIPTextEncoderL.safetensors"
lda_checkpoint = "checkpoints/lda.safetensors"
image_encoder_checkpoint = "checkpoints/dinov2_vitl14_reg4_pretrain.safetensors"
ip_adapter_checkpoint = "/home/isamu/checkpoints/uncond_not_weighted/step60000.safetensors"
input_pertubation = 0.0
loss_scaler="legacy"

[unet]
requires_grad = false

[image_proj]

[ip_adapter]
image_encoder_type = "dinov2_vitl14_reg4"
resolution = 518
scale = 1.0
inference_scale = 1.0
use_timestep_embedding = true
fine_grained = true
initialize_model = true
initializer_range = 0.02
use_rescaler = true
weighted_sum = false
use_unconditional_image_embedding = true

[training]
duration = {"number" = 100000000, "unit" = "step"}
seed = 9752
batch_size = 32
gradient_accumulation = {"number" = 2, "unit" = "step"}
evaluation_interval = {"number" = 10000, "unit" = "step"}
evaluation_seed = 9752
dtype = "bfloat16"
device="cuda"
gradient_clipping_max_norm=2.0

[optimizer]
optimizer = "AdamW8bit"  # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
# learning_rate = 5e-4
learning_rate = 1e-4
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[lr_scheduler]
type = "ConstantLR"
update_interval = "1:step"
# max_steps = 2000
# eta_min = 1e-6
# warmup = "500:step"

[dataset]
horizontal_flip_probability = 0.0
image_drop_rate = 0.05
text_drop_rate = 0.05
text_and_image_drop_rate = 0.05
cache_dir = "/home/isamu/tmp"
shuffle = false
cache_limit = "150gb"
is_mosaic = true
is_webdataset = false
only_image = false
dataset_workers = 4
predownload = 15000
download_retry = 2
download_timeout = 5

[save_adapter]
checkpoint_steps = 10000
save_folder = "/home/isamu/checkpoints/uncond_default_fixed_amp"

[test_ldm]
num_inference_steps = 30
num_images_per_prompt = 1
prompts = [
    "A dog flying over a castle",
    "Cute cats watching a tv",
    "A ferret on top of a sky scraper",
    "Pink flamingo playing soccer"
]
validation_image_paths = [
    "checkpoints/frida.jpg",
    "checkpoints/cute_cats.jpg",
    "checkpoints/ferret.jpg",
    "checkpoints/pink_flamingo.jpg"
]
[compute_grad_norms]

[compute_param_norms]
